### ISSUE TITLE
Locating buildings' timeseries data

### ISSUE THREAD

**Issue by jkatofsky** [plastering/plastering#6]
Hi again!

Apologies in advance if I'm missing something; I'm trying to test Building Adapter on Plaster's included buildings, but in trying to use `timeseries_init.py`, I could not any find csv files of timeseries data to provide the script.

Are these located somewhere outside the Plastering repository, or are they not yet available?

Thank you!

**Comment by jbkoh** [comment]
Hey Josh,

Sorry the timeseries data is not available for sharing. Our campus is restricting the data sharing and it's hard to reinitiate the conversation these days. If you want I can share the data format so that you can fill out yours.

**Comment by jkatofsky** [comment]
No problem, I understand. Anything you could share to help with fitting our data to Plaster's format would be very helpful. Thank you!
